version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket ${TEST_LAMBDA_BUCKET_NAME} --output-template-file outputTemplate.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml
