AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sample lambda function
Globals:
  Function:
    MemorySize: 128
    Timeout: 3
    Handler: app.lambdaHandler
    Runtime: nodejs14.x
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sample/
